### ISSUE TITLE
 Cannot find module 'windicss/colors' in vscode

### ISSUE THREAD

**Issue by ppusapati** [windicss/windicss-intellisense#63]
Every time I open VS Code I get this message. Tried by reinstalling windicss extension but didn't work. 

OS: Ubuntu 20.10 64 Bit
Vscode: v1.54.3
node: 12.18.3

`ERROR: Error: Cannot find module 'windicss/colors'
Require stack:
- /home/projects/tailwind.config.cjs
- /home/.vscode/extensions/voorjaar.windicss-intellisense-0.7.2/out/extension.js
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js
Error: Cannot find module 'windicss/colors'
Require stack:
- /home/projects/SLNES/UI_test/tailwind.config.cjs
- /home/dhanvi/.vscode/extensions/voorjaar.windicss-intellisense-0.7.2/out/extension.js
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js
	at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1019:15)
	at Module._load (internal/modules/cjs/loader.js:895:27)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.s._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27167)
	at Function._._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:23919)
	at Function.W._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4637)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/usr/share/code/resources/app/out/vs/loader.js:3:12287)
	at Object.<anonymous> (/home/projects/SLNES/UI_test/tailwind.config.cjs:1:78)
	at Module.u._compile (/usr/share/code/resources/app/out/vs/loader.js:3:12841)
	at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
	at Module.load (internal/modules/cjs/loader.js:1039:32)
	at Module._load (internal/modules/cjs/loader.js:932:14)
	at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
	at Function.s._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:27167)
	at Function._._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:106:23919)
	at Function.W._load (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:96:4637)
	at Module.require (internal/modules/cjs/loader.js:1079:19)
	at v (/usr/share/code/resources/app/out/vs/loader.js:3:12287)
	at /home/dhanvi/.vscode/extensions/voorjaar.windicss-intellisense-0.7.2/out/extension.js:26358:38
	at step (/home/dhanvi/.vscode/extensions/voorjaar.windicss-intellisense-0.7.2/out/extension.js:62:23)
	at Object.next (/home/dhanvi/.vscode/extensions/voorjaar.windicss-intellisense-0.7.2/out/extension.js:43:53)
	at fulfilled (/home/dhanvi/.vscode/extensions/voorjaar.windicss-intellisense-0.7.2/out/extension.js:33:58)
	at processTicksAndRejections (internal/process/task_queues.js:97:5)
Windi CSS Intellisense is now active!`

**Comment by alexanderniebuhr** [comment]
i actaully can't reproduce. please provide more information

**Comment by alexanderniebuhr** [comment]
ohh wait.. can you show us your `windi.config.js`?

**Comment by alexanderniebuhr** [comment]
I actually cannot reproduce it... super strange

**Comment by ppusapati** [comment]
No issues, problem was resolved after uninstalling this vscode extension. voorjaar.windicss-intellisense Thank you

**Comment by alexanderniebuhr** [comment]
It should work with the latest of the extension with not problem!

**Comment by alexanderniebuhr** [comment]
@ppusapati so does it work with newest update of the extension?

**Comment by ppusapati** [comment]
No it didn't.  Removed tailwind intellicense and tried with no luck.

**Comment by beetaa** [comment]
> @ppusapati so does it work with newest update of the extension?

newest version, every time I update files relies on windicss, error shown up.

![image](https://user-images.githubusercontent.com/5688224/113832310-114efd80-97bb-11eb-8026-9636f98973e6.png)

**Comment by beetaa** [comment]
when import `windics/colors`,  the same.

**Comment by alexanderniebuhr** [comment]
@beetaa have you install `windicss` as dependency?

**Comment by beetaa** [comment]
@alexanderniebuhr yes, dependency is the key point of the issue. because I use vite-plugin-windicss instead of windicss, the extension cannot find the module. when I install windicss and add it to the devDependencies, there's no more errors shown. thank you so much.

@ppusapati  are you also using vite-plugin-windicss?

**Comment by antfu** [comment]
@beetaa are you using `pnpm`?

**Comment by antfu** [comment]
@alexanderniebuhr kinda think, instead of a warning message, we can do it a bit non-distractive way, like warning sign in the status bar (like ESLint) and click to see the error log.

**Comment by ppusapati** [comment]
> @alexanderniebuhr yes, dependency is the key point of the issue. because I use vite-plugin-windicss instead of windicss, the extension cannot find the module. when I install windicss and add it to the devDependencies, there's no more errors shown. thank you so much. but it should be better if the extension can handle the condition like this. @antfu 
> 
> @ppusapati  are you also using vite-plugin-windicss?

Am not using windicss for now. Because of this error and other thing is its not identifying dynamically generated css. Will come back to windicss at later stage.

**Comment by beetaa** [comment]
> @beetaa are you using `pnpm`?

yes, I am using pnpm.

**Comment by antfu** [comment]
Might be the hoisting problem of pnpm, maybe try to install `windicss` as the top-level dependencies? I will update docs for that

**Comment by alexanderniebuhr** [comment]
once I get done the linked PR later today, it will have fallback for missing windicss as deps
