### ISSUE TITLE
(plugin-utils): type: module not working

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/windicss-intellisense#96]
there is still an issue with `type: module` in package.json, seems to be an type issue @antfu any idea?

```
⚠ ERROR: Invalid host defined options
⚠ ERROR: TypeError: Invalid host defined options
	at eval (eval at loadConfiguration (c:\Users\Alexander\.vscode-insiders\extensions\voorjaar.windicss-intellisense-0.11.5\out\extension.js:36061:27), <anonymous>:3:1)
	at loadConfiguration (c:\Users\Alexander\.vscode-insiders\extensions\voorjaar.windicss-intellisense-0.11.5\out\extension.js:36064:35)
```

**Comment by alexanderniebuhr** [comment]
https://github.com/windicss/windicss-intellisense/blob/f731c023deb9081d436839c3b3b926cfd2f2b853/src/lib/core.ts#L17-L29
